sudo: false

language: node_js
node_js:
  - '10'
  - '11'
  - '12'
  - '13'

install:
  - npm install
before_script:
  - npm run setup
script:
  - commitlint-travis
  - npm run test:jest

jobs:
  include:
    - stage: codecov
      node_js: lts/*
      script:
        - npm run test:cov
    - stage: release
      node_js: lts/*
      script: ':' # noop, skips tests
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          # Branch selection is managed by semantic-release in .releaserc.yml
          all_branches: true
          repo: JuroOravec/instance-manager

notifications:
  email:
    on_success: never

env:
  global:
    # GH token - semantic-release/github
    - secure: EU7BVyvMCHyDnV7PWOaLmGvfwaIxZNgkMymgU4OP0nJ7FxubLvZ2uBver4IZNTmlp6EwYe+apKUDZY6fJey+N6rCXR4qdPAvIey5Nh1SMHXbl1eYl7grvmyK29buSOF7+nCYREAsF06ZdqIikzf1rEaCUD+3FF1MrbUiJXf6xbojEcQf0F9uTFGJk2VXFkaTTKzCB6OqJ43zLY318WjkeIOsdbPAjD5kMaod3BY12U2jKe4NwMJU9m4Onx4FEeXJ+V920Avv6VdC8JsdE7Q1tteLpuUBE3HIK5Cj6s0lI6IUww7xTaI7tMaQz0lFuk8YaUw7eg78tlCD+liGvXpmT4mGfDQMKurIvdbVspLr4SqUe7NBe61Aq7yyLgtWUf1342e5lSJosGFAbjuowzn3edcxkZzAsTdLWZReCwjAkIwCBS4+/HeRm/r0VmFZf3YqDX4rXnw7JI/KPevLlc5rr4KgAVGHGGEj31ZhASIyc9T9D4ZkChjM/Thn8dSX1yG6r2AblTWxDbgSVh00iQi1ucUQfn5o6qi+nuKJWknENmPeFpIRv73pIa+GLZu2hrf4CYqO8w2zxzTzotNLkePRYOHFeGIsgEH5pDwL4BgXZcXyn/9NKeL8sGtevyTOjSWyBZR6u6MEB0eBgMGmxiF8c9eKYzOZwK3vhfSG4UTOfrg=
    # NPM token - semantic-release/npm
    - secure: QZv5tOtLIR7s4tQHOIu2wLM3VkV15Tb99qwEIfXsYtQXBF0hiO8VegHKN/fLnh9DxJzuASqlNa0RK+7cx1I6y1dVb78bNIY5nOFKSsubxBsoUXF3vgp6QPihjzeIlanlOH7AgW+pb7269KomOnkT4DOu5Gns+C9p27e9ZUfHZ8mH3zkfclPycLqW08ImUPv/5ipZCgLyEtWPsFFRPzJi61ZLTZ8coGub/zPHvkft1OGk7XsBXqb28m6/ccS8B+b5qxvoDTNVTIitJeyemki7eXnEjnZeMD8iKRuArCuCtV7hjaUOLZc7rKKszH8LnGl+V7j+7g6EsMrIkR5jPspJXmT2TO1QdHj2y0zKrPeczj2Rr5JHacWcXtvadladOKysbd1+ECvBxS+W/18iqB9HfdRXEIzojKUJ7QDwk65hWI4QRwilMshAw1K4twV/b8JOagkAZLPEHgY9sSZqaisbf+QEcutPDN3jDNRqYjJt+sCGKnmyzQO/+yRY3VUko9wZVULuqeBA8wHHKQmzWDVDso4Qsg8471m5z6tTstw4kR9uVha3PVIYbCPw76AiKUU8px9vp4ySnhG5tkybFB2bEZ9PBwMkcmPtYp7vO+lGZbnysEu+It02VSdzJ4roRy2R+m/vZEgRyQZDkVj7ckzDy5Nk6o78y4KVdcH/xOXMjyk=
