language: node_js
node_js:
  - 10
before_script:
  - npm run setup
  - npm run build
after_success:
  - codecov:upload
deploy:
  provider: npm
  email: juraj.oravec.josefson@gmail.com
  api_key:
    secure: MrpVM32AR2Jml5jK+EojD1xuJJtystQLLNN6tntdfvYT3Lm6i6S798yNcLfx48FjFMH/qCQSH6pmDHrOmIsKaBhOQ7+3R6Xg+5ZrQGXWv6XqI8aVdmJo+EI5KCfxnS17IdRBYrhKB+Fxoe4hCQElqcbNAXWeHFJSWKq3kl74C4djTcC6H+RWDXwy1zlm7jLmynuSGCB2FeOf6efJujqwr0rKiz96vO2CuN4C3OaNuXeFWeAguTpdygJA/jKBqA0HTFd41gf2IqFAZPIOxR9Ly4s3C7B1gR2w8BUwjGkf3Lr0fn5/RLmPE68MDHUOLShzYJJbrq87VNS37bDo4gawaaVxDFssJuNfxXXgLDNQ7OhNSTVfQuEKP3y+EFsAZ2JJIKZkrcR9Z46bkTBUiasyTHDAtLOxYHMPLYFSXATe26ixqmCBOE68COnAQmvfMOHdqUEpVl0iZ9J82ilvZyFs0NjYc9Ts/uhLcLL7jRVJw280a+rWdGd7RC6WUWaTif0y/LHK7LNswLvXsmiCZVmffm96gDEEXFPIIhciXVsghlRzLAk8sJsb6VN7Plj0XsOhQLQWJJoQa+TJAtsZLj1WNRp72maMQUjm0oZDlgsm1BvHrBe76Rk5KoIpPEPhD3riURKbB8gbQhM1fKvpbfu5rQzSdOXlsZUwHzggGpJ4s2M=
  on:
    tags: true
    repo: JuroOravec/instance-manager
