sudo: false

language: node_js
node_js:
  - '10'
  - '11'
  - '12'
  - '13'

install:
  - npm install
before_script:
  - npm run setup
script:
  - commitlint-travis
  - npm test

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          # Branch selection is managed by semantic-release in .releaserc.yml
          all_branches: true
          repo: JuroOravec/instance-manager

notifications:
  email:
    on_success: never

env:
  global:
    - secure: EU7BVyvMCHyDnV7PWOaLmGvfwaIxZNgkMymgU4OP0nJ7FxubLvZ2uBver4IZNTmlp6EwYe+apKUDZY6fJey+N6rCXR4qdPAvIey5Nh1SMHXbl1eYl7grvmyK29buSOF7+nCYREAsF06ZdqIikzf1rEaCUD+3FF1MrbUiJXf6xbojEcQf0F9uTFGJk2VXFkaTTKzCB6OqJ43zLY318WjkeIOsdbPAjD5kMaod3BY12U2jKe4NwMJU9m4Onx4FEeXJ+V920Avv6VdC8JsdE7Q1tteLpuUBE3HIK5Cj6s0lI6IUww7xTaI7tMaQz0lFuk8YaUw7eg78tlCD+liGvXpmT4mGfDQMKurIvdbVspLr4SqUe7NBe61Aq7yyLgtWUf1342e5lSJosGFAbjuowzn3edcxkZzAsTdLWZReCwjAkIwCBS4+/HeRm/r0VmFZf3YqDX4rXnw7JI/KPevLlc5rr4KgAVGHGGEj31ZhASIyc9T9D4ZkChjM/Thn8dSX1yG6r2AblTWxDbgSVh00iQi1ucUQfn5o6qi+nuKJWknENmPeFpIRv73pIa+GLZu2hrf4CYqO8w2zxzTzotNLkePRYOHFeGIsgEH5pDwL4BgXZcXyn/9NKeL8sGtevyTOjSWyBZR6u6MEB0eBgMGmxiF8c9eKYzOZwK3vhfSG4UTOfrg=
    - secure: BxQMqO8SDB789h9Vove6NFscUtSI6MvXWA19Jp9q/sLCBTN0MVRYPtaUKBiv09LCiprh694/BdYLENkGpThO7uWkAUyyYWh+JkSZIsPUiTG1VItLFxkdDXCKRaNlaoD/VVHH5h2hmI1QgYTIko6iYttf4rwTw45rGFjer3/eri91/FqDaVnFI+vsHXElZsooIA8lA3X/7uMYw619TIlFv8L0Hg//tK3B+zgyWHgNNOJZdWbjuF48OoK1iVivOX5rrP5BAEJqeoG+WUSlxpG7muGvHoQTH212I6H1idS8EYAcIW9jrP5ntOb5Im97Cq7haEVnJ5VVlXXbotBmjdwITjDtjguWjtD3dAR+KtdqqP6g18nH/KVxBNey4+RTnno+qiGMG/Ba4I74b7qB1zied7EFiR4sMbqdcerKShv2VkstwNNwf1Ml73XM7dsYiHdIvToTlInzLrxQeys2hKMR+wP4DcDwv3mP24DEpgSxa/c90oZxgPQCMqMsq3MZw/Lqdp8ZfP53GdheMNYDkoB0Jl3eNxJ21kIElzeMD90rv2qm55tL2gagjQnGBN+BJ0FA/FFYWPeWrmX1ZoMIVzdGvLV3w8iH9S8d8LIg1LhflVMEA2/3Es15PuTLaubDydSaORoayhCezEpYMVDJskYa+1qASaTkmhCn7t/Q+6fqNa0=
