os: linux
dist: xenial

branches:
  only:
    - master
  except:
    - /temp\/.*/

language: node_js
node_js:
  - '10'
  - '11'
  - '12'
  - '13'

before_install:
  # Configure signed git commits from within Travis CI, see:
  # https://github.com/semantic-release/git/tree/905f113a577c55cd9bb0a37ea3504d9e8ee2dfa2#gpg-signature
  # Decrypt git_gpg_keys.asc.enc key into /tmp/git_gpg_keys.asc
  - openssl aes-256-cbc -K $encrypted_44fd1061a48b_key -iv $encrypted_44fd1061a48b_iv -in ./config/travis-ci/git_gpg_keys.asc.enc -out /tmp/git_gpg_keys.asc -d
  # Make sure only the current user can read the keys
  - chmod 600 /tmp/git_gpg_keys.asc
  # Import the gpg key
  - gpg --batch --yes --import /tmp/git_gpg_keys.asc
  # Create a script that pass the passphrase to the gpg CLI called by git
  - echo '/usr/bin/gpg --passphrase ${GPG_PASSPHRASE} --batch --no-tty "$@"' > /tmp/gpg-with-passphrase && chmod +x /tmp/gpg-with-passphrase
  # Configure git to use the script that passes the passphrase
  - git config gpg.program "/tmp/gpg-with-passphrase"
  # Configure git to sign the commits and tags
  - git config commit.gpgsign true
  # Configure git to use your GPG key
  - git config --global user.signingkey ${GPG_KEY_ID}
install:
  - npm install
  # Remove installation side effects (like updated package-lock.json)
  - git reset --hard HEAD
before_script:
  - npm run setup
script:
  - commitlint-travis
  - npm run validate

jobs:
  include:
    - stage: codecov
      node_js: lts/*
      script:
        - npm run test:cov

    - stage: update CHANGELOG.md
      if: type = pull_request
      node_js: lts/*
      script: npx semantic-release # runs with PR-specific config

    - stage: release
      node_js: lts/*
      script: ':' # noop, skips tests
      deploy:
        edge: true
        provider: script
        script: npx semantic-release
        on:
          # Branch selection is managed by semantic-release in .releaserc.yml
          all_branches: true
          repo: JuroOravec/instance-manager

notifications:
  email:
    on_success: never

env:
  global:
    # GH token - semantic-release/github
    - secure: EU7BVyvMCHyDnV7PWOaLmGvfwaIxZNgkMymgU4OP0nJ7FxubLvZ2uBver4IZNTmlp6EwYe+apKUDZY6fJey+N6rCXR4qdPAvIey5Nh1SMHXbl1eYl7grvmyK29buSOF7+nCYREAsF06ZdqIikzf1rEaCUD+3FF1MrbUiJXf6xbojEcQf0F9uTFGJk2VXFkaTTKzCB6OqJ43zLY318WjkeIOsdbPAjD5kMaod3BY12U2jKe4NwMJU9m4Onx4FEeXJ+V920Avv6VdC8JsdE7Q1tteLpuUBE3HIK5Cj6s0lI6IUww7xTaI7tMaQz0lFuk8YaUw7eg78tlCD+liGvXpmT4mGfDQMKurIvdbVspLr4SqUe7NBe61Aq7yyLgtWUf1342e5lSJosGFAbjuowzn3edcxkZzAsTdLWZReCwjAkIwCBS4+/HeRm/r0VmFZf3YqDX4rXnw7JI/KPevLlc5rr4KgAVGHGGEj31ZhASIyc9T9D4ZkChjM/Thn8dSX1yG6r2AblTWxDbgSVh00iQi1ucUQfn5o6qi+nuKJWknENmPeFpIRv73pIa+GLZu2hrf4CYqO8w2zxzTzotNLkePRYOHFeGIsgEH5pDwL4BgXZcXyn/9NKeL8sGtevyTOjSWyBZR6u6MEB0eBgMGmxiF8c9eKYzOZwK3vhfSG4UTOfrg=
    # NPM token - semantic-release/npm
    - secure: QZv5tOtLIR7s4tQHOIu2wLM3VkV15Tb99qwEIfXsYtQXBF0hiO8VegHKN/fLnh9DxJzuASqlNa0RK+7cx1I6y1dVb78bNIY5nOFKSsubxBsoUXF3vgp6QPihjzeIlanlOH7AgW+pb7269KomOnkT4DOu5Gns+C9p27e9ZUfHZ8mH3zkfclPycLqW08ImUPv/5ipZCgLyEtWPsFFRPzJi61ZLTZ8coGub/zPHvkft1OGk7XsBXqb28m6/ccS8B+b5qxvoDTNVTIitJeyemki7eXnEjnZeMD8iKRuArCuCtV7hjaUOLZc7rKKszH8LnGl+V7j+7g6EsMrIkR5jPspJXmT2TO1QdHj2y0zKrPeczj2Rr5JHacWcXtvadladOKysbd1+ECvBxS+W/18iqB9HfdRXEIzojKUJ7QDwk65hWI4QRwilMshAw1K4twV/b8JOagkAZLPEHgY9sSZqaisbf+QEcutPDN3jDNRqYjJt+sCGKnmyzQO/+yRY3VUko9wZVULuqeBA8wHHKQmzWDVDso4Qsg8471m5z6tTstw4kR9uVha3PVIYbCPw76AiKUU8px9vp4ySnhG5tkybFB2bEZ9PBwMkcmPtYp7vO+lGZbnysEu+It02VSdzJ4roRy2R+m/vZEgRyQZDkVj7ckzDy5Nk6o78y4KVdcH/xOXMjyk=
    # GPG signature env vars
    # https://github.com/semantic-release/git/tree/905f113a577c55cd9bb0a37ea3504d9e8ee2dfa2#gpg-signature
    # GPG_PASSPHRASE
    - secure: EBCq0s1zjIS2R7KDLdsz09gEBhGbB+yiAw/SblVBZFI3Wu8CxSFGLfULPgxPHgstpGZq7m2QCi/1wHYe76e0se4Fey9lXsj6ngQs2H1G+MS1WGU2k46eOdt06H58td1kx1iIgq/vkJoIOfUhavG7OtuLx6Spv5CmnG+5WNKJx8iktYEHh+oT7cJ9LIknwetyro5d1rpSefy+NkF8PSnwOm9/8mI5kS77vpnlOUQ6Bc9TrZi3S9wtwcL4GaraR8/e80C8k4gQcPDi1x/aArigcNCiXQNuwz04PiyFpAP2pLPy8lJi79kG0J0qoy5kJ4x0hfE1PZfuwl36XA38lA84i0Q5RG5mdSgwMCWPDC5iOf7rDIPD9/BvTaU2Np7DbpIJ3ruKAJROHYk4ZHbJE1aeCHU+QCPR1jUk82QPDhq5Dc9AhEOQutanvm+Upf1FuMm45cIfyLLrpuqrPnwMgdSfsUSGi0nyBYWwh+0FjkxLxCubJrslABN3/25KmtRJUPkl0pKAtczkK5w/gwy6nCUEdTmrVXBIWIKdJ2Rq+y/qHTiojBsYU6YR2BtLwqtxA2N0hz+67mM59CyZfQKVBZrYSYnKgqsLBfixz0oV4NgYvmO3CKh39Jqpkm/ktPFvQM/+vRZAy5J5r1+5tfiioN7CIz0aCT+onalZBJlG0D4OXEk=
    # GPG_KEY_ID
    - secure: eXiup0sv9w8nn+us+6Cc0WxLkUeILY3vp+CBFqhUFOPoDBPyNtjYDOmPhOTh03k8VJm/DKuEpxg0SVtcmJg/8q96YRuXIIozfXFVSSIrNK/jeH2oV2fKR5ghdAYToxG+JYBW2iNvZmIQdZ4Yv+auO/XM2kCemR+kyD25UxD+4uoDRpnfIuwf+nTH3VSaL1Z+Kz/bqyzLkIJWJ6o043AzF0Vl7LVNd7FPoCF5Ds1CNBnh7I0C3cGSjO1blTEejYfep9HsR73bjoWgqMWIdwZhzPHI6+Psdu097Pn7nayc9uCNLCEhP+N5QFdzKOAjudVsw70bYkBvGGjLdeJ981hogC2V36KK+2mUmwG+Z88UDCHtOmbRiNL6j959r4bYIAqZQ39yKXqMq+yS2Dkqwy1we5RwYQsdSjA3R+O7ZHef7jXnXt+O96oefF2Y4fqkFksn78AnbdLcW6cvyOcznuHImfbNCbhMxi6Wz+R2AKrBc/Grq7nQ3qK7ua4Bs4w+2VIEDw4kKFAsTUz0A2AVpzfMUC8z6UOw+P5r6x1+fmcWOZGFAc8k26Nk9sSb/yTi5ZdxiPa8AyZ/nVLQ51FAWo7Uen2HG6Bhx2Y5UAxeMBK0NsfNy4rFQ9Ykk16clZpvQH4mw9otDWsHn4tshvp9OG2n3Y/xUvxEur3RKbNtKA5DQQU=
    # GIT_EMAIL
    - secure: LzvraQQo4XPQDSonqZmZ5nVD08BF3XC1kkjEjtFD+7LdiUu622zhr3g38OZH/7c2Q7hZ6EXoyGM08NK1uktNkXMP5xS87AcBU3j477wpkweXEo67AwaKNmuKzI8Ng5sO8ausr+I/PUotIDzEszSe00DOn6RA/SSr2bR8g1/dId4vKHBPWNCfpeFKclE0mI3CV4TRlX5E0kinqghgm3CrfZeRzfzwwAf+cdcH9UCHwgIUnoWq2DnHpLcX6aztPdl/eeBi9O5Hvi8fy8Z+IF5IoqkDALy80+uMWn2JprlVOaZt6NanUsHtRYVEqRJIBO5Y40Os9MhZl5L3jhhBsT30NfPVFbvy8vo5wHmIwiuwAnjYyfOGAFMpKncXaOyTi5Jfagr10vkFqL0hpfQp0rgsHLtrkg4NWSJf73lJt4T/Gmrh80CkpbfboEcI4ThAOYTydrI4B1ckrSkP1xP8vuOKBS/o+qcepOp73NCBGGS+9jkOEWHumbCXttTmU96GPqrWpFQ0HxLhu5dTKTrjXvIxtM1xVaSBtuzMyCPkikjZh/YNfCUhJq9RKqZ1ZRUF/0WX5aAaQbunu8wDy/qyHRqKa8BSUw3SRpPJ208eMExKHdY7XtQamQ2J+aM/mTAQ03K+UIk6trMMxYMQc2r2gUuH8APoUqkKk+ERxFWLRkj+eT8=
    # GIT_USERNAME
    - secure: F7W49pqv4qH2z/hMyYLkJ+JDUhJEOqSuYFgqAgYraQpsJbxHaBQZmeySMqF4Ca1hUARVwM0bN/Kxx6MOdOOdKPk7bOgnOyPM6mS1mSFxRZIoCezMCDhebOaoMOQ8+s2FXb23vajuEXoaj+OSS347DzGW0TjJ/vzZRatycjzrQFWMmEme5lZcMgR4JBiSjtl05heyxSRMLLfEqB5GKPjJC58BMtuls5lTL3RpTqNNj2kbG09oE5lutsR+cVGSGmryCB/OJvw03ev93poE/L4XP60Z63hCxWo64+AV8W4gMU6Ce5N9FDxiagn/0nHNExwxHmOtFrmAsDZqP16oYQobv5HSDfx0aRU/suW1/wZQmp/PqMN4ue4nlQp+Skp+SR0pJu9RRuh+8W+YuXZJGju6zI2nnViSxQRAIXXegCGrrHg8Anx+qPbkcBiPTNN03OhsVmYnmPyRLvUVwVu8jQcFaXM1UHNr91enKea2PBbx5l2OCVPur4vQ1fy67QEJ3tM2CbkSuolJSvQdQ9iQPD5kK6iEh06lIFg2qLTRm0UsyX4eUCzP3c7UvfD5h7E/fQ2Ztgsl8cB1d4SSX1MmWoA2rm2ch6IECj9lozLguLHphz6X9Vvp8OZxWNLe3KcEXL+kVTs5r4kIiMF0QIyTMNx2bSa6qGADPJE4jLMyPxbuCtg=
    # GIT_COMMITTER_NAME (to have signed commits from semantic-release)
    - secure: FRZ2yRVgFDZ1Z/dEtN89GGtug+rJrbJRUhO/cLNuJ4FEaTQuoSWiVYCrtDhB2F/Jz0apuyMESG1ABMwja0sR+onPTWW0iwGj9RDNJrzpOmWhgI1bHjDs1dseQsxhpBeQcO2Vf6CUWlWLo3sn0S5+tiOLsAvjcEsvYAwuYyURQowecWz10TghjbljLS4s9eAUEVvub/tWwAlaGEWBukuk/kab7kRJGXGOZLDvLiF7ALW9G/j+I5qA5hmejtWKOxj89dYW4V4z4sJH62ccPTht0eQFIBPmkX0akDpe+tQfiajsFbbvsNFLN+Y/tU/izcmeCGyH8lOH9VaenN1TtDKa0/q2v09b/666fb5G9UV+Xy+WbdvwF9yEOv6eYMyw1B2CVL7cbP6zsBaRFKUvUaXpRUFcpGN6jtNtBEt55VGb9jSprtISeyPR1WDlrSWYOcjs3KMQha1hGwRxXejkiKrRilSXFPGJfRvJBTPnWMRIUqTSiME56sLm2mJKXvlNV+nKdScYtcVIhIe0Pr3ZZhwTeTrIU9AmDfQD9Z6j+uxvhZyhJUZn1BL2j7WF5dVDsu5vWo76SoBhyd6laEYBdYg81JnYpgeCfrZDeLBqPCFpiswA6UwXEDzhcKKHVmX9u5yMyP5bcPQgveCj0j2FNbFdl8RNkBsWxiSAU3lp4h82KCA=
    # GIT_COMMITTER_EMAIL (to have signed commits from semantic-release)
    - secure: pqooP9t3unXMCKwk6qhnL52WTSy1jib7OrJlIJBYyNHzRUeL5IMLo6CBt5ml1/1+KRbofwZt21Xt+FX6HDj+hNt+gs+vJwQy2ZJjGSbaKJUR+NJZQkuQfVOGjj5HYPqTTJZj3FLopFUBBApFL9OKbMpYdN3mUAB49n6RKSbstk+f2/qCkgg2qJZn9To4YEBr4Ckg2drQX59UorNbw3XSSqqFahMJLDzZ2g6glmXS99+aDuRreVxyJjRrJWqpv7xdNjCy+jQ/ecO/bEuq3Czr6pVI//yNBCQU5OIUHTtQ2nXmefKZzPAtLKePWxZKnh9KaEDGitIgOrj5w4jEWeIxiRqqD4+T2vLvq7vKHaHf+fSvXvxrrVvI1bcAwG4aM3+Gg1C504POA91SAW0wgSyzp0sjMrSrT1VuSSESsc1Q02tSOM2ug3nF0Z+KQg5w9f+kw5MVwCIwt+W0WfIFrb8/WdKOhtZtrkWrLTtpNU4X/11gMuGBHaw5xq07xClZxnpF1KEcXBJyEZ8YTssQ5a97pRooN7BcIVbPy/Y0wk8sJjm6JflulSGLctus+kudHmcPBHNB8jVDD/aZ3NzAF71tQx7eOI/LeIG9oFmhGJHHrzDoaVbKu31fSwV77L2orsOZB6bDif41/2GP0vQ8ZCQzX3cfarW+BV9rkA3/ZFbGjXE=
